import { Info, Sparkles } from "lucide-react";

interface AIContentDisclaimerProps {
  variant?: "inline" | "banner" | "subtle";
  className?: string;
}

export function AIContentDisclaimer({ variant = "subtle", className = "" }: AIContentDisclaimerProps) {
  if (variant === "banner") {
    return (
      <div className={`bg-zinc-900/50 border border-zinc-800 rounded-lg p-4 ${className}`} data-testid="ai-content-disclaimer-banner">
        <div className="flex items-start gap-3">
          <div className="w-8 h-8 rounded-full bg-primary/20 flex items-center justify-center flex-shrink-0">
            <Sparkles className="w-4 h-4 text-primary" />
          </div>
          <div>
            <p className="text-sm font-medium text-foreground mb-1">AI-Generated Content</p>
            <p className="text-xs text-zinc-400 leading-relaxed">
              Content generated by AI is provided for creative inspiration and assistance. 
              Please review all generated content for accuracy, appropriateness, and alignment with your vision before publishing.
              You retain full ownership of content you create or modify.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (variant === "inline") {
    return (
      <div className={`flex items-center gap-2 text-xs text-zinc-500 ${className}`} data-testid="ai-content-disclaimer-inline">
        <Info className="w-3 h-3" />
        <span>AI-generated content. Review before publishing.</span>
      </div>
    );
  }

  return (
    <p className={`text-[10px] text-zinc-600 ${className}`} data-testid="ai-content-disclaimer-subtle">
      AI-generated content for review
    </p>
  );
}

export function MedicalDisclaimer({ className = "" }: { className?: string }) {
  return (
    <div className={`bg-amber-500/10 border border-amber-500/20 rounded-lg p-4 ${className}`} data-testid="medical-disclaimer">
      <div className="flex items-start gap-3">
        <Info className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-medium text-amber-500 mb-1">Medical Information Notice</p>
          <p className="text-xs text-zinc-400 leading-relaxed">
            This content is for educational and informational purposes only and is not intended as medical advice. 
            Always consult with qualified healthcare professionals before making decisions about your health or treatment. 
            Individual results may vary, and past recovery outcomes do not guarantee future results.
          </p>
        </div>
      </div>
    </div>
  );
}
